[[preface]]
= Preface

This is my fifth Ruby on Rails book. My first one was for Rails 3.2.
As much as Rails 5.1 is the best Rails version ever I want this book
to be my best Rails book ever. I shorted a lot of examples to make it
lighter and faster to read.

I wrote this book for developers who learn best by following clean examples.
I don’t like the idea of coding one big single application throughout a book
but prefer smaller stand-alone code examples. Therefore you can skip a couple of
pages or even complete chapters without losing context.

Don’t let people fool you into believing that Ruby on Rails is easy to
learn. It is not! It's probably the best and most effective framework
to develop web applications but it is hard to understand in the
beginning. The worst mistake of all is to not learn Ruby before diving
into Ruby on Rails. To avoid it this book starts with the
xref:ruby-basics[basics of Ruby]. You will not become a Ruby guru after
reading it but you’ll understand the basic ideas and that is important.

Shameless plug: Please contact me by e-mail to stefan.wintermeyer@amooma.de
if you need Ruby on Rails consulting or training.

Have fun with Ruby on Rails!

_Stefan Wintermeyer_

PS: I post updates about this book and Rails in general at https://twitter.com/wintermeyer
